---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# CIGM

<!-- badges: start -->
<!-- badges: end -->

The package provides functions for recovering finite resolution approximations of conditional independence graphs of Gaussian processes.

## Installation

You can install the development version of CIGM from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("kgwstat/CIGM")
```

## Example

This is a basic example which considers the Brownian motion covariance:

```{r example}
library(CIGM)
## Brownian motion example
Range <- seq(0, 1, length.out = 300)
CovFn <- function(x, y) {min(x, y)}
M <- outer(Range, Range, Vectorize(CovFn))
P <- PrecisionOpMatrix(M, 20)
```


Here is the plot:
```{r pressure, echo = FALSE}
library(viridisLite)
coul <- viridis(100)
lattice::levelplot(P, xlab = "x", ylab = "y", main = "Precision Operator Matrix for Brownian Motion", col.regions = coul)
```

